version: '3.7'

services:
    php:
        build:
            context: .
            dockerfile: .devops/php/Dockerfile
        container_name: alexishayat-me-php
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "9000:9000"
        networks:
            - alexishayat-me-network

    nginx:
        build:
            context: .
            dockerfile: .devops/nginx/Dockerfile
        container_name: alexishayat-me-nginx
        restart: unless-stopped
        ports:
            - "8190:443"
        networks:
            - alexishayat-me-network

networks:
    alexishayat-me-network:
        driver: bridge
