#name: Deploy on OVH
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: AzenoX/ovh-deploy-hosting-action@master
#        env:
#          OVH_HOSTING_USER: ${{ secrets.OVH_HOSTING_USER }}
#          OVH_HOSTING_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
#          OVH_HOSTING_DOMAIN: ${{ secrets.OVH_HOSTING_DOMAIN }}
#          REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
#          DOMAIN: ${{ secrets.DOMAIN }}

