name: Deploy on OVH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.OVH_SSH_PRIVATE_KEY }}
          known_hosts: 'known_hosts'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.OVH_SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Rsync Deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          remote_path: /var/www/alexishayat.me/
          remote_host: ${{ secrets.OVH_SSH_HOST }}
          remote_user: ${{ secrets.OVH_SSH_USER }}
          remote_key: ${{ secrets.OVH_DEPLOY_KEY }}
