name: Deploy on OVH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.OVH_SSH_PRIVATE_KEY }}
          known_hosts: 'known_hosts'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.OVH_SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz --exclude '.git' --chown=github-alexishayat:www-data --chmod=Dg=rwx,Fg=rwx ./ ${{ secrets.OVH_SSH_USER }}@${{ secrets.OVH_SSH_HOST }}:/var/www/alexishayat
        .me/
